### ISSUE TITLE
Add sample backend for testing

### ISSUE THREAD

**Issue by Himasnhu-AT** [Himasnhu-AT/prodAPI#19]
Cover API to ensure that it works seamlessly with other things. 

API to create:

> [!Important]
> - requires header
> - requires params
> - requires body
> ? and their combinations

**Comment by RiyaRaj28** [comment]
@Himasnhu-AT assign this to me, I can do it

**Comment by Himasnhu-AT** [comment]
@RiyaRaj28 pushed sample

I didn't test API's, some packages might be missing

the file `sample-endpoints.json` have endpoint that we can utilize

**Comment by RiyaRaj28** [comment]
> @RiyaRaj28 pushed sample
> 
> I didn't test API's, some packages might be missing
> 
> the file `sample-endpoints.json` have endpoint that we can utilize

Okay, will check
